server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/venus/h2db/venus
    username: admin
    password: 123456

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
      elasticsearch:
        cluster-nodes: localhost:9200
        repositories:
          enabled: true
        properties:
          path:
            logs: ./elasticsearch/log
            data: ./elasticsearch/data

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 5MB

  cache:
    type: caffeine

logging:
  file: ./logs/venus.log
